-- core
require('core.mappings')
require('core.plugins')
require('core.options')
require('core.treesitter')
require('core.nvim-tree')
require('core.bufferline')
require('core.lualine')
require('core.telescope')
require('core.web-devicons')
require('core.luasnip')
require('core.completions')
